language: node_js
node_js:
  - "node"
after_success:
- ./node_modules/.bin/jscoverage . lib-cov
- ./node_modules/.bin/mocha YOUR_TESTS/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
