language: node_js
node_js:
    - "6"
    - "5"
    - "4"
script:
- ./node_modules/.bin/jscoverage lib lib-cov
- ./node_modules/.bin/mocha test/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
after_success:
coveralls