/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['min.js']) {
  _$jscoverage['min.js'] = [];
  _$jscoverage['min.js'][1] = 0;
  _$jscoverage['min.js'][2] = 0;
  _$jscoverage['min.js'][3] = 0;
  _$jscoverage['min.js'][4] = 0;
  _$jscoverage['min.js'][6] = 0;
}
_$jscoverage['min.js'].source = ["module<span class=\"k\">.</span>exports <span class=\"k\">=</span> <span class=\"k\">function</span> min<span class=\"k\">(</span>array<span class=\"k\">)</span><span class=\"k\">{</span>","    <span class=\"k\">var</span> min <span class=\"k\">=</span> array<span class=\"k\">[</span><span class=\"s\">0</span><span class=\"k\">];</span>","    <span class=\"k\">for</span><span class=\"k\">(</span><span class=\"k\">var</span> i<span class=\"k\">=</span><span class=\"s\">0</span> <span class=\"k\">;</span> i<span class=\"k\">&lt;</span>array<span class=\"k\">.</span>length <span class=\"k\">;</span> i<span class=\"k\">++)</span><span class=\"k\">{</span>","        min <span class=\"k\">=</span> array<span class=\"k\">[</span>i<span class=\"k\">]</span> <span class=\"k\">&lt;</span> min <span class=\"k\">?</span> array<span class=\"k\">[</span>i<span class=\"k\">]</span> <span class=\"k\">:</span> min<span class=\"k\">;</span>","    <span class=\"k\">}</span>","    <span class=\"k\">return</span> min<span class=\"k\">;</span>","<span class=\"k\">}</span>"];
_$jscoverage['min.js'][1]++;
module.exports = (function min(array) {
  _$jscoverage['min.js'][2]++;
  var min = array[0];
  _$jscoverage['min.js'][3]++;
  for (var i = 0; (i < array.length); (i++)) {
    _$jscoverage['min.js'][4]++;
    min = ((array[i] < min)? array[i]: min);
}
  _$jscoverage['min.js'][6]++;
  return min;
});
